//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerDesktopBingX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_MAIN {
            get {
                return ((bool)(this["SW_MAIN"]));
            }
            set {
                this["SW_MAIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_LCO {
            get {
                return ((bool)(this["SW_LCO"]));
            }
            set {
                this["SW_LCO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_DB_LCO {
            get {
                return ((bool)(this["SW_DB_LCO"]));
            }
            set {
                this["SW_DB_LCO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_S {
            get {
                return ((bool)(this["SW_S"]));
            }
            set {
                this["SW_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_DB_S {
            get {
                return ((bool)(this["SW_DB_S"]));
            }
            set {
                this["SW_DB_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_NG {
            get {
                return ((bool)(this["SW_NG"]));
            }
            set {
                this["SW_NG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_DB_NG {
            get {
                return ((bool)(this["SW_DB_NG"]));
            }
            set {
                this["SW_DB_NG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_ADD1 {
            get {
                return ((bool)(this["SW_ADD1"]));
            }
            set {
                this["SW_ADD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_DB_ADD1 {
            get {
                return ((bool)(this["SW_DB_ADD1"]));
            }
            set {
                this["SW_DB_ADD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_ADD2 {
            get {
                return ((bool)(this["SW_ADD2"]));
            }
            set {
                this["SW_ADD2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_DB_ADD2 {
            get {
                return ((bool)(this["SW_DB_ADD2"]));
            }
            set {
                this["SW_DB_ADD2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TB_KEY {
            get {
                return ((string)(this["TB_KEY"]));
            }
            set {
                this["TB_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TB_SECRET {
            get {
                return ((string)(this["TB_SECRET"]));
            }
            set {
                this["TB_SECRET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TB_DBNAME {
            get {
                return ((string)(this["TB_DBNAME"]));
            }
            set {
                this["TB_DBNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TB_LOCALHOST {
            get {
                return ((string)(this["TB_LOCALHOST"]));
            }
            set {
                this["TB_LOCALHOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TB_NAME_ADD1 {
            get {
                return ((string)(this["TB_NAME_ADD1"]));
            }
            set {
                this["TB_NAME_ADD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TB_NAME_ADD2 {
            get {
                return ((string)(this["TB_NAME_ADD2"]));
            }
            set {
                this["TB_NAME_ADD2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TB_NOT_BOT_TELEGRAM_TOKEN {
            get {
                return ((string)(this["TB_NOT_BOT_TELEGRAM_TOKEN"]));
            }
            set {
                this["TB_NOT_BOT_TELEGRAM_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TB_LOG_BOT_TELEGRAM_TOKEN {
            get {
                return ((string)(this["TB_LOG_BOT_TELEGRAM_TOKEN"]));
            }
            set {
                this["TB_LOG_BOT_TELEGRAM_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_NOT_CHANGE_LCO {
            get {
                return ((bool)(this["SW_NOT_CHANGE_LCO"]));
            }
            set {
                this["SW_NOT_CHANGE_LCO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_NOT_CHANGE_NG {
            get {
                return ((bool)(this["SW_NOT_CHANGE_NG"]));
            }
            set {
                this["SW_NOT_CHANGE_NG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_NOT_CHANGE_ADD1 {
            get {
                return ((bool)(this["SW_NOT_CHANGE_ADD1"]));
            }
            set {
                this["SW_NOT_CHANGE_ADD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_NOT_CHANGE_ADD2 {
            get {
                return ((bool)(this["SW_NOT_CHANGE_ADD2"]));
            }
            set {
                this["SW_NOT_CHANGE_ADD2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_NOT_CHANGE_S {
            get {
                return ((bool)(this["SW_NOT_CHANGE_S"]));
            }
            set {
                this["SW_NOT_CHANGE_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_LOG_LCO {
            get {
                return ((bool)(this["SW_LOG_LCO"]));
            }
            set {
                this["SW_LOG_LCO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_LOG_NG {
            get {
                return ((bool)(this["SW_LOG_NG"]));
            }
            set {
                this["SW_LOG_NG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_LOG_S {
            get {
                return ((bool)(this["SW_LOG_S"]));
            }
            set {
                this["SW_LOG_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_LOG_ADD1 {
            get {
                return ((bool)(this["SW_LOG_ADD1"]));
            }
            set {
                this["SW_LOG_ADD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_LOG_ADD2 {
            get {
                return ((bool)(this["SW_LOG_ADD2"]));
            }
            set {
                this["SW_LOG_ADD2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UD_NOT_CHANGE_LCO {
            get {
                return ((decimal)(this["UD_NOT_CHANGE_LCO"]));
            }
            set {
                this["UD_NOT_CHANGE_LCO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UD_NOT_CHANGE_NG {
            get {
                return ((decimal)(this["UD_NOT_CHANGE_NG"]));
            }
            set {
                this["UD_NOT_CHANGE_NG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UD_NOT_CHANGE_S {
            get {
                return ((decimal)(this["UD_NOT_CHANGE_S"]));
            }
            set {
                this["UD_NOT_CHANGE_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UD_NOT_CHANGE_ADD1 {
            get {
                return ((decimal)(this["UD_NOT_CHANGE_ADD1"]));
            }
            set {
                this["UD_NOT_CHANGE_ADD1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UD_NOT_CHANGE_ADD2 {
            get {
                return ((decimal)(this["UD_NOT_CHANGE_ADD2"]));
            }
            set {
                this["UD_NOT_CHANGE_ADD2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_NOT_BOT_TELEGRAM {
            get {
                return ((bool)(this["SW_NOT_BOT_TELEGRAM"]));
            }
            set {
                this["SW_NOT_BOT_TELEGRAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_LOG_BOT_TELEGRAM {
            get {
                return ((bool)(this["SW_LOG_BOT_TELEGRAM"]));
            }
            set {
                this["SW_LOG_BOT_TELEGRAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_BACKUP {
            get {
                return ((bool)(this["SW_BACKUP"]));
            }
            set {
                this["SW_BACKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TB_DIRECTORY_BACKUP {
            get {
                return ((string)(this["TB_DIRECTORY_BACKUP"]));
            }
            set {
                this["TB_DIRECTORY_BACKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UD_DAYS_BACKUP {
            get {
                return ((decimal)(this["UD_DAYS_BACKUP"]));
            }
            set {
                this["UD_DAYS_BACKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UD_STORE_BACKUP {
            get {
                return ((decimal)(this["UD_STORE_BACKUP"]));
            }
            set {
                this["UD_STORE_BACKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_BACKUP_TELEGRAM {
            get {
                return ((bool)(this["SW_BACKUP_TELEGRAM"]));
            }
            set {
                this["SW_BACKUP_TELEGRAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DTP_BACKUP {
            get {
                return ((string)(this["DTP_BACKUP"]));
            }
            set {
                this["DTP_BACKUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_DAILYREPORT {
            get {
                return ((bool)(this["SW_DAILYREPORT"]));
            }
            set {
                this["SW_DAILYREPORT"] = value;
            }
        }
    }
}
